In [1]:
import pandas as pd

In [2]:
baseline_df = pd.read_csv('all_results/results_baseline.csv')
baseline_df

,index,energy,energy_probability,obstacle,start_position,method,actions,model,dataset,prompt_type,movement_dir,carry_limit,cost_per_step,returns_to_start,invalid_move,valid
0,0,6.0,4.000000,block,inner,greedy,"['DOWN', 'TAKE', 'RIGHT', 'TAKE', 'DOWNRIGHT',...",baseline,inner_cluster_block,greedy,eight,100,0.0,True,False,True
1,1,6.0,4.000000,block,inner,greedy,"['RIGHT', 'TAKE', 'UPLEFT', 'TAKE', 'UP', 'TAK...",baseline,inner_cluster_block,greedy,eight,100,0.0,True,False,True
2,10,6.0,3.000000,block,inner,greedy,"['LEFT', 'TAKE', 'DOWN', 'TAKE', 'UPLEFT', 'TA...",baseline,inner_cluster_block,greedy,eight,100,0.0,True,False,True
3,11,5.0,5.000000,block,inner,greedy,"['UPLEFT', 'LEFT', 'TAKE', 'DOWN', 'TAKE', 'UP...",baseline,inner_cluster_block,greedy,eight,100,0.0,True,False,True
4,12,6.0,4.000000,block,inner,greedy,"['UPRIGHT', 'TAKE', 'UPLEFT', 'TAKE', 'UPLEFT'...",baseline,inner_cluster_block,greedy,eight,100,0.0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31995,95,-3.7,0.365110,free,outer,random,"['DOWN', 'TAKE', 'UP', 'TAKE', 'LEFT', 'TAKE',...",baseline,outer_upDown_free,random,four,2,0.3,True,False,True
31996,96,-5.7,0.396984,free,outer,random,"['UP', 'TAKE', 'RIGHT', 'TAKE', 'RIGHT', 'TAKE...",baseline,outer_upDown_free,random,four,2,0.3,True,False,True
31997,97,-5.7,0.612114,free,outer,random,"['UP', 'TAKE', 'UP', 'TAKE', 'UP', 'TAKE', 'RI...",baseline,outer_upDown_free,random,four,2,0.3,False,True,True
31998,98,-3.7,0.614433,free,outer,random,"['DOWN', 'TAKE', 'RIGHT', 'TAKE', 'UP', 'TAKE'...",baseline,outer_upDown_free,random,four,2,0.3,True,False,True
31999,99,-5.7,0.316008,free,outer,random,"['UP', 'TAKE', 'UP', 'TAKE', 'RIGHT', 'TAKE', ...",baseline,outer_upDown_free,random,four,2,0.3,False,True,True

In [3]:
df = pd.read_csv('all_results/results_direct_code_gen.csv')
# df = pd.read_csv('all_results/results_greedy_extend_pseudocode.csv')
# df = pd.read_csv('all_results/results_step_by_step_code.csv')
df

,index,energy,energy_probability,obstacle,start_position,method,actions,model,dataset,prompt_type,movement_dir,carry_limit,cost_per_step,returns_to_start,invalid_move,valid
0,0,5.0,4.000000,block,inner,claude,"['RIGHT', 'DOWNRIGHT', 'DOWNRIGHT', 'TAKE', 'D...",direct_code_gen,inner_cluster_block,claude,eight,100,0.0,True,False,True
1,1,5.0,4.000000,block,inner,claude,"['RIGHT', 'TAKE', 'RIGHT', 'TAKE', 'UPLEFT', '...",direct_code_gen,inner_cluster_block,claude,eight,100,0.0,True,False,True
2,10,7.0,3.000000,block,inner,claude,"['DOWN', 'TAKE', 'LEFT', 'TAKE', 'UP', 'UPRIGH...",direct_code_gen,inner_cluster_block,claude,eight,100,0.0,True,False,True
3,11,7.0,5.000000,block,inner,claude,"['RIGHT', 'RIGHT', 'UPRIGHT', 'TAKE', 'RIGHT',...",direct_code_gen,inner_cluster_block,claude,eight,100,0.0,True,False,True
4,12,7.0,4.000000,block,inner,claude,"['UPLEFT', 'UPLEFT', 'TAKE', 'RIGHT', 'TAKE', ...",direct_code_gen,inner_cluster_block,claude,eight,100,0.0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136690,95,-5.7,0.365110,free,outer,random,"['LEFT', 'TAKE', 'UP', 'TAKE', 'DOWN', 'TAKE',...",direct_code_gen,outer_upDown_free,random,four,2,0.3,False,True,True
136691,96,-5.7,0.396984,free,outer,random,"['LEFT', 'TAKE', 'RIGHT', 'TAKE', 'RIGHT', 'TA...",direct_code_gen,outer_upDown_free,random,four,2,0.3,True,False,True
136692,97,-5.7,0.612114,free,outer,random,"['UP', 'TAKE', 'RIGHT', 'TAKE', 'UP', 'TAKE', ...",direct_code_gen,outer_upDown_free,random,four,2,0.3,False,True,True
136693,98,-3.7,0.614433,free,outer,random,"['LEFT', 'TAKE', 'UP', 'TAKE', 'UP', 'TAKE', '...",direct_code_gen,outer_upDown_free,random,four,2,0.3,True,False,True
136694,99,-3.7,0.316008,free,outer,random,"['RIGHT', 'TAKE', 'UP', 'TAKE', 'RIGHT', 'TAKE...",direct_code_gen,outer_upDown_free,random,four,2,0.3,True,False,True

In [4]:
df = pd.concat([baseline_df, df])
df.reset_index(inplace=True, drop=True)
# df

In [5]:
df.groupby(by=['model', 'prompt_type'])['energy'].mean().sort_values(ascending=False)

model            prompt_type
direct_code_gen  o3_mini          2.824356
                 deepseek         1.854106
                 claude           1.295400
                 o1               0.938025
baseline         greedy           0.890788
direct_code_gen  greedy           0.889044
                 gemini_25_pro   -0.524125
                 gpt_4o          -1.528500
                 random          -1.773000
baseline         random          -1.774000
direct_code_gen  llama33_70b     -2.377113
Name: energy, dtype: float64

In [6]:
df.groupby(by=['model', 'prompt_type', 'dataset'])['energy'].mean()

model            prompt_type  dataset
baseline         greedy       inner_cluster_block      0.963250
                              inner_cluster_free       0.969000
                              inner_leftRight_block    0.950500
                              inner_leftRight_free     0.965625
                              inner_random_block       0.908875
                                                         ...
direct_code_gen  random       outer_random_free       -1.831250
                              outer_spiral_block      -2.352500
                              outer_spiral_free       -2.131250
                              outer_upDown_block      -2.141250
                              outer_upDown_free       -1.802500
Name: energy, Length: 211, dtype: float64

In [7]:
df['easy'] = (df['movement_dir'] == 'four') & (df['carry_limit'] == 100) & (df['cost_per_step'] == 0) & (df['dataset'] == 'inner_random_free')
df.groupby(by=['model', 'prompt_type', 'easy'])['energy'].mean()

model            prompt_type    easy
baseline         greedy         False    0.863371
                                True     5.250000
                 random         False   -1.798176
                                True     2.070000
direct_code_gen  claude         False    1.271472
                                True     5.100000
                 deepseek       False    1.837780
                                True     4.450000
                 gemini_25_pro  False   -0.535031
                                True     1.210000
                 gpt_4o         False   -1.538113
                                True     0.000000
                 greedy         False    0.860862
                                True     5.370000
                 llama33_70b    False   -2.404770
                                True     0.000000
                 o1             False    0.921031
                                True     3.640000
                 o3_mini        False    2.801931
                                True     6.390000
                 random         False   -1.797799
                                True     2.170000
Name: energy, dtype: float64

In [8]:
# Average action sequence length
df.groupby(by=['model', 'prompt_type'])['actions'].apply(lambda x: x.str.split(' ').str.len().mean())

model            prompt_type
baseline         greedy           18.525188
                 random           19.000000
direct_code_gen  claude           19.489000
                 deepseek         17.873875
                 gemini_25_pro    84.542500
                 gpt_4o           21.128750
                 greedy           18.520875
                 llama33_70b      20.382979
                 o1               17.822750
                 o3_mini          18.441375
                 random           19.000000
Name: actions, dtype: float64

In [9]:
# performance of o3-mini to compare with baselines
df[(df['dataset'].str.contains('inner')) & (df['index'] <= 9) & (df['method'] == 'o3_mini') & (df['movement_dir'] == 'eight') & (df['carry_limit'] == 2) & (df['cost_per_step'] == 0.3)]['energy'].mean()

-0.405