In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('all_results/results_iterative_instances.csv')
df

,index,energy,energy_probability,obstacle,start_position,method,actions,model,dataset,prompt_type,movement_dir,carry_limit,cost_per_step,returns_to_start,invalid_move,valid
0,0,5.0,4.000000,block,inner,claude_a_basic,"['RIGHT', 'DOWNRIGHT', 'DOWNRIGHT', 'TAKE', 'D...",iterative_instances,inner_cluster_block,claude_a_basic,eight,100,0.0,True,False,True
1,1,5.0,4.000000,block,inner,claude_a_basic,"['RIGHT', 'TAKE', 'RIGHT', 'TAKE', 'UPLEFT', '...",iterative_instances,inner_cluster_block,claude_a_basic,eight,100,0.0,True,False,True
2,10,7.0,3.000000,block,inner,claude_a_basic,"['DOWN', 'TAKE', 'LEFT', 'TAKE', 'UP', 'UPRIGH...",iterative_instances,inner_cluster_block,claude_a_basic,eight,100,0.0,True,False,True
3,11,7.0,5.000000,block,inner,claude_a_basic,"['RIGHT', 'RIGHT', 'UPRIGHT', 'TAKE', 'RIGHT',...",iterative_instances,inner_cluster_block,claude_a_basic,eight,100,0.0,True,False,True
4,12,7.0,4.000000,block,inner,claude_a_basic,"['UPLEFT', 'UPLEFT', 'TAKE', 'RIGHT', 'TAKE', ...",iterative_instances,inner_cluster_block,claude_a_basic,eight,100,0.0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367779,95,-0.2,0.365110,free,outer,o3_mini_c,"['LEFT', 'TAKE', 'LEFT', 'TAKE', 'RIGHT', 'RIG...",iterative_instances,outer_upDown_free,o3_mini_c,four,2,0.3,True,False,True
367780,96,-2.8,0.396984,free,outer,o3_mini_c,"['RIGHT', 'RIGHT', 'RIGHT', 'TAKE', 'UP', 'TAK...",iterative_instances,outer_upDown_free,o3_mini_c,four,2,0.3,True,False,True
367781,97,-1.4,0.612114,free,outer,o3_mini_c,"['UP', 'TAKE', 'LEFT', 'TAKE', 'RIGHT', 'DOWN'...",iterative_instances,outer_upDown_free,o3_mini_c,four,2,0.3,True,False,True
367782,98,-3.0,0.614433,free,outer,o3_mini_c,"['LEFT', 'TAKE', 'LEFT', 'LEFT', 'LEFT', 'LEFT...",iterative_instances,outer_upDown_free,o3_mini_c,four,2,0.3,True,False,True
367783,99,-3.0,0.316008,free,outer,o3_mini_c,"['RIGHT', 'TAKE', 'RIGHT', 'RIGHT', 'TAKE', 'R...",iterative_instances,outer_upDown_free,o3_mini_c,four,2,0.3,True,False,True

In [15]:
df.groupby(by=['model', 'prompt_type'])['energy'].mean()

model                prompt_type
iterative_instances  claude_a_basic       1.295400
                     claude_b             2.604719
                     claude_c             2.780850
                     claude_d             2.605619
                     deepseek_a_basic     1.854106
                     deepseek_b           1.586725
                     gemini_25_a_basic   -0.524125
                     gemini_25_b          3.097006
                     gemini_25_c          3.214150
                     gemini_25_d          3.222069
                     gemini_25_e          3.007062
                     gpt_4o_a_basic      -1.531947
                     gpt_4o_b            -1.452061
                     gpt_4o_c            -1.013249
                     gpt_4o_d            -0.787873
                     gpt_4o_e            -0.448208
                     gpt_4o_f            -0.448208
                     o1_a_basic           0.938025
                     o1_b                 2.824356
                     o1_c                 2.590375
                     o3_mini_a_basic      2.824356
                     o3_mini_b            2.897925
                     o3_mini_c            1.411775
Name: energy, dtype: float64

In [16]:
df = df[df['model'] == 'iterative_instances']
df = df[df['prompt_type'].str.contains('gemini_25_d')]

In [17]:
df.sort_values(by=['energy']).head(3)

,index,energy,energy_probability,obstacle,start_position,method,actions,model,dataset,prompt_type,movement_dir,carry_limit,cost_per_step,returns_to_start,invalid_move,valid
357383,99,-1.4,0.316008,free,outer,gemini_25_d,"['RIGHT', 'TAKE', 'UP', 'RIGHT', 'TAKE', 'DOWN...",iterative_instances,outer_upDown_free,gemini_25_d,four,2,0.3,True,False,True
247110,61,-1.4,0.370063,free,outer,gemini_25_d,"['UP', 'UP', 'TAKE', 'LEFT', 'TAKE', 'DOWN', '...",iterative_instances,outer_leftRight_free,gemini_25_d,four,2,0.3,True,False,True
155140,45,-1.4,0.694299,block,inner,gemini_25_d,"['DOWN', 'DOWN', 'TAKE', 'LEFT', 'TAKE', 'UP',...",iterative_instances,inner_upDown_block,gemini_25_d,four,2,0.3,True,False,True

In [18]:
for i, row in df.sort_values(by=['energy']).head(5).iterrows():
    print(row['dataset'], row['index'])

outer_upDown_free 99
outer_leftRight_free 61
inner_upDown_block 45
inner_cluster_free 23
outer_upDown_block 54

In [19]:
df.groupby(by=['prompt_type', 'dataset'])['energy'].mean().sort_values(ascending=False)

prompt_type  dataset
gemini_25_d  inner_leftRight_free     3.538125
             inner_upDown_free        3.517750
             inner_random_free        3.489500
             inner_spiral_free        3.426375
             inner_upDown_block       3.424250
             inner_leftRight_block    3.423625
             outer_leftRight_free     3.381875
             inner_cluster_free       3.358125
             inner_random_block       3.340875
             inner_cluster_block      3.328875
             inner_spiral_block       3.303875
             outer_random_free        3.264250
             outer_upDown_free        3.261375
             outer_random_block       3.206750
             outer_upDown_block       3.129000
             outer_leftRight_block    3.105250
             outer_cluster_free       2.823625
             outer_spiral_free        2.821750
             outer_cluster_block      2.675000
             outer_spiral_block       2.621125
Name: energy, dtype: float64

In [20]:
df.groupby(by=['model', 'prompt_type', 'dataset'])['energy'].mean()

model                prompt_type  dataset
iterative_instances  gemini_25_d  inner_cluster_block      3.328875
                                  inner_cluster_free       3.358125
                                  inner_leftRight_block    3.423625
                                  inner_leftRight_free     3.538125
                                  inner_random_block       3.340875
                                  inner_random_free        3.489500
                                  inner_spiral_block       3.303875
                                  inner_spiral_free        3.426375
                                  inner_upDown_block       3.424250
                                  inner_upDown_free        3.517750
                                  outer_cluster_block      2.675000
                                  outer_cluster_free       2.823625
                                  outer_leftRight_block    3.105250
                                  outer_leftRight_free     3.381875
                                  outer_random_block       3.206750
                                  outer_random_free        3.264250
                                  outer_spiral_block       2.621125
                                  outer_spiral_free        2.821750
                                  outer_upDown_block       3.129000
                                  outer_upDown_free        3.261375
Name: energy, dtype: float64

In [21]:
df['easy'] = (df['movement_dir'] == 'four') & (df['carry_limit'] == 100) & (df['cost_per_step'] == 0) & (df['dataset'] == 'inner_random_free')
df.groupby(by=['model', 'prompt_type', 'easy'])['energy'].mean()

model                prompt_type  easy
iterative_instances  gemini_25_d  False    3.197868
                                  True     7.070000
Name: energy, dtype: float64

In [22]:
# Get average action sequence length
df.groupby(by=['model', 'prompt_type'])['actions'].apply(lambda x: x.str.split(' ').str.len().mean())

model                prompt_type
iterative_instances  gemini_25_d    17.795813
Name: actions, dtype: float64

In [23]:
df[(df['dataset'].str.contains('inner')) & (df['index'] <= 9) & (df['method'].str.contains('o3_mini') | df['method'].str.contains('greedy') | df['method'].str.contains('random')) & (df['movement_dir'] == 'eight') & (df['carry_limit'] == 2) & (df['cost_per_step'] == 0.3)].groupby(['method'])['energy'].mean()

Series([], Name: energy, dtype: float64)

In [24]:
df[(df['dataset'].str.contains('inner')) & (df['index'] <= 9) & (df['method'].str.contains('o3_mini') | df['method'].str.contains('greedy') | df['method'].str.contains('random')) & (df['movement_dir'] == 'eight') & (df['carry_limit'] == 2) & (df['cost_per_step'] == 0.3)].groupby(['method'])['energy'].std()

Series([], Name: energy, dtype: float64)